tunnel: eyJhIjoiMDUxMTk3MzdiYTA2MGE3M2M2MjcxNjI2M2ViZWEwMjkiLCJ0IjoiNzIyMzFlNzEtMTdmZi00NWFiLTk1OGMtYjRjYzhlMjU2NmExIiwicyI6IlkyVTBNV05pWXpRdE5UYzNOaTAwWVdJNUxXSmxOR1F0TUdNd1ptUmlZVEZoTm1RNCJ9
credentials-file: /path/to/credentials.json

ingress:
  - hostname: t1.seed.us.kg
    service: http://localhost:5000
  - service: http_status:404
