tunnel: 72231e71-17ff-45ab-958c-b4cc8e2566a1
credentials:
  apiToken: eyJhIjoiMDUxMTk3MzdiYTA2MGE3M2M2MjcxNjI2M2ViZWEwMjkiLCJ0IjoiNzIyMzFlNzEtMTdmZi00NWFiLTk1OGMtYjRjYzhlMjU2NmExIiwicyI6IlkyVTBNV05pWXpRdE5UYzNOaTAwWVdJNUxXSmxOR1F0TUdNd1ptUmlZVEZoTm1RNCJ9

ingress:
  - hostname: t1.seed.us.kg
    service: http://localhost:7860
  - service: http_status:404
